/**
 * Routing manifest renderer.
 *
 * Produces the per-target top-level file (CLAUDE.md / GEMINI.md / .cursor/rules/paytm.mdc)
 * that the AI tool reads first. Structure:
 *
 *   1. Generated banner identifying the bundle version.
 *   2. Optional per-target preamble (frontmatter for Cursor's .mdc, etc.).
 *   3. The verbatim contents of routing/PREAMBLE.md (global rules + decision tree).
 *   4. Auto-generated skill index table (name, path, triggers).
 */

import { readFileSync } from "node:fs";
import { packagePath } from "../manifest.mjs";

function targetPreamble(target) {
  // Cursor expects YAML frontmatter on .mdc files; other targets accept plain markdown.
  if (target.format === "skill-md" && target.routing_file?.endsWith(".mdc")) {
    return [
      "---",
      "description: Paytm Payment Gateway integration skills - routing manifest",
      "alwaysApply: true",
      "---",
      "",
    ].join("\n");
  }
  return "";
}

function renderSkillIndex(manifest) {
  const lines = [];
  lines.push("");
  lines.push("## Skill index (auto-generated)");
  lines.push("");
  lines.push("| Skill | Path | Activation triggers |");
  lines.push("|---|---|---|");
  for (const s of manifest.skills || []) {
    const triggers = (s.triggers || []).map((t) => "`" + t + "`").join(", ");
    lines.push(`| **${s.name}** | \`${s.name}/SKILL.md\` | ${triggers || "_(none declared)_"} |`);
  }
  lines.push("");
  lines.push("Each skill folder contains its own `SKILL.md` (always loaded when the skill activates) and optionally `references/REFERENCE.md` (lazy-loaded on demand).");
  return lines.join("\n");
}

export function renderRoutingManifest({ manifest, target }) {
  const banner = `<!-- generated by paytm-skills@${manifest.version} for target ${target.id} - do not edit by hand -->\n\n`;
  const tp = targetPreamble(target);

  let preamble = "";
  if (manifest.routing_preamble) {
    try {
      preamble = readFileSync(packagePath(manifest.routing_preamble), "utf8");
    } catch {
      preamble = "(routing preamble missing - regenerate skill bundle)";
    }
  }

  return banner + tp + preamble + "\n" + renderSkillIndex(manifest) + "\n";
}
