/**
 * Routing manifest renderer.
 *
 * Produces the per-target top-level file (CLAUDE.md / GEMINI.md / .cursor/rules/paytm.mdc)
 * that the AI tool reads first. Structure:
 *
 *   1. Generated banner identifying the bundle version.
 *   2. Optional per-target preamble (frontmatter for Cursor's .mdc, etc.).
 *   3. The verbatim contents of routing/PREAMBLE.md (global rules + decision tree).
 *   4. Auto-generated skill index table (name, path, triggers).
 */

import { readFileSync } from "node:fs";
import { packagePath } from "../manifest.mjs";

function targetPreamble(target, manifest) {
  // Cursor's .mdc files use a specific frontmatter shape.
  if (target.format === "skill-md" && target.routing_file?.endsWith(".mdc")) {
    return [
      "---",
      "description: Paytm Payment Gateway integration skills - routing manifest",
      "alwaysApply: true",
      "---",
      "",
    ].join("\n");
  }

  // SKILL.md (Claude Code, Codex, anything following the Claude convention)
  // requires YAML frontmatter with name + description so the loader registers it.
  if (target.routing_file === "SKILL.md" || target.routing_file?.endsWith("/SKILL.md")) {
    const triggers = collectAllTriggers(manifest).join('", "');
    return [
      "---",
      `name: ${manifest.name}`,
      "description: >",
      `  Paytm Payment Gateway integration skills bundle - one-time payments (JS Checkout), subscriptions (UPI Autopay /`,
      `  NATIVE_SUBSCRIPTION), payment links, dynamic QR codes, native mobile SDKs (All-in-One + Custom for Android/iOS),`,
      `  S2S webhooks, refunds, getting-started + troubleshooting. Loaded modularly; this entry contains the routing`,
      `  decision tree and global rules. Trigger on Paytm-specific tokens like "paytmchecksum", "txnToken",`,
      `  "CHECKSUMHASH", "paytmpayments.com", "/theia/api/", "NATIVE_SUBSCRIPTION", "WEBSTAGING", or any mention of`,
      `  integrating Paytm or migrating to Paytm from another gateway.`,
      "---",
      "",
    ].join("\n");
  }

  return "";
}

function collectAllTriggers(manifest) {
  const set = new Set();
  for (const s of manifest.skills || []) {
    for (const t of s.triggers || []) set.add(t);
  }
  return [...set];
}

function renderSkillIndex(manifest) {
  const lines = [];
  lines.push("");
  lines.push("## Skill index (auto-generated)");
  lines.push("");
  lines.push("| Skill | Path | Activation triggers |");
  lines.push("|---|---|---|");
  for (const s of manifest.skills || []) {
    const triggers = (s.triggers || []).map((t) => "`" + t + "`").join(", ");
    lines.push(`| **${s.name}** | \`${s.name}/SKILL.md\` | ${triggers || "_(none declared)_"} |`);
  }
  lines.push("");
  lines.push("Each skill folder contains its own `SKILL.md` (always loaded when the skill activates) and optionally `references/REFERENCE.md` (lazy-loaded on demand).");
  return lines.join("\n");
}

export function renderRoutingManifest({ manifest, target }) {
  const banner = `<!-- generated by paytm-agent-skills@${manifest.version} for target ${target.id} - do not edit by hand -->\n\n`;
  const tp = targetPreamble(target, manifest);

  let preamble = "";
  if (manifest.routing_preamble) {
    try {
      preamble = readFileSync(packagePath(manifest.routing_preamble), "utf8");
    } catch {
      preamble = "(routing preamble missing - regenerate skill bundle)";
    }
  }

  // YAML frontmatter (when present) MUST come first - the skill loader rejects
  // it otherwise. Banner + content follow.
  return tp + banner + preamble + "\n" + renderSkillIndex(manifest) + "\n";
}
